[package]
name = "pyforge"
version = "0.1.0"
edition = "2021"
description = "PyForge — Python 项目管家，uv 的强力补充"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourname/pyforge"
readme = "README.md"
rust-version = "1.75"

[[bin]]
name = "pyforge"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
git2 = { version = "0.20", default-features = false }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "5"
toml = "0.8"
fs2 = "0.4"
clap_complete = "4"
ureq = "3"
axum = "0.8"
webbrowser = "1"

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"
reqwest = { version = "0.12", features = ["blocking"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
